version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - jonchang
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  assignees:
  - jonchang
