name: Docker
on:
  schedule:
    - cron: '0 10 * * 0'  # At 10:00 on Sunday
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: |
          ghcr.io/jonchang/fishtreeoflife-docker
        tags: |
          type=schedule
          type=ref,event=branch
          type=sha

    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      if: github.event_name != 'pull-request'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
